disabled_rules:
  - inclusive_language
  - todo
  - opening_brace

opt_in_rules:
  - empty_count
  - empty_string
  - file_header

excluded:
  - SwiftLint/Common/3rdPartyLib
  - .build
  - Package.swift
  - Tests/LinuxMain.swift
  - Tests/MusicNotationTests/XCTestManifests.swift

analyzer_rules:
  - capture_variable
  - unused_declaration
  - unused_import

line_length:
  warning: 2000
  error: 240
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true

function_body_length:
  warning: 500
  error: 700

function_parameter_count:
  warning: 6
  error: 8

type_body_length:
  warning: 500
  error: 800

file_length:
  warning: 1000
  error: 1500
  ignore_comment_only_lines: true

cyclomatic_complexity:
  warning: 22
  error: 25

identifier_name:
  max_length:
    warning: 60
    error: 80
  min_length:
    error: 3
  excluded:
    - up
    - row
    - key
    - id
    - url
    - uri
    - URI
    - URL

reporter: "xcode"

file_header:
  required_pattern: |
                    \/\/
                    \/\/\t.*?\.swift
                    \/\/\t.*?
                    \/\/
                    \/\/\tCreated by .*? on \d{4}-\d{2}-\d{2}\.
                    \/\/\tCopyright © \d{4}(-\d{4})* .*?\. All rights reserved\.
                    \/\/

final_class:
  regex: '^class [a-zA-Z\d]+[^{]+\{'
  message: "Classes should be marked as final whenever possible. If you actually need it to be subclassable, just add `// swiftlint:disable:next final_class`."
    